[general]
live_config_reload = true
working_directory = "None"

import = [ 
  "~/.config/alacritty/colors.toml",
  "~/.config/alacritty/keybinds.toml"
]

[window]
title = "Alacritty"
decorations = "none"
blur = true
opacity = 0.9
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape = "Underline"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "Misc Tamsyn"
normal.style = "Misc Tamsyn"
size = 10.0

[font.bold]
family = "Misc Tamsyn"
style = "Bold"

[font.italic]
family = "Misc Tamsyn"
style = "Italic"
